"""Added Database

Revision ID: c0a81373d996
Revises: 
Create Date: 2022-03-24 11:18:12.432001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0a81373d996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_token',
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('user',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('doctor',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('degree', sa.String(length=127), nullable=False),
    sa.Column('medical_profession', sa.String(length=127), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('details_filled', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('hospital',
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('details_filled', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('patient',
    sa.Column('nhid', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('details_filled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('nhid')
    )
    op.create_table('staff',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('doctor_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('hospital_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_uuid'], ['doctor.uuid'], ),
    sa.ForeignKeyConstraint(['hospital_uuid'], ['hospital.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('patient')
    op.drop_table('hospital')
    op.drop_table('doctor')
    op.drop_table('user')
    op.drop_table('blacklisted_token')
    # ### end Alembic commands ###
